### PR TITLE
2.0 tabs and layered section boxes

### PR DESCRIPTION
**Pull request by gusreiber**
OK, Tom, likely this is still not as small a chunk as you might like.
Included here:
- **cleanup for the tabs themselves**: I removed the toggle to hide the text filter and made the tabs look a little nice and more grounded to the form
- **general alignment cleanup in the form**: did some CSS judo to make things line-up a good bit better
  -**added block highlighting for repeating regions**
  -**fixed what seemed like a bug with the 'general' group injection**: The name input was being stripped out

### CODE REVIEW

**Comment by gusreiber** [comment]
@daniel-beck @tfennelly @abayer @kohsuke ...added some more stuff to Tom's tabs. If these seems like it is passing mustard here with you all, I will PR on up the foodchain.

**Comment by gusreiber** [comment]
https://youtu.be/m9c84zCGsiM

Above is a video demo

**Comment by tfennelly** [comment]
@gusreiber Sorry Gus ... you created this PR against the wrong branch.

**Comment by tfennelly** [comment]
Replacement: https://github.com/jenkinsci/jenkins/pull/2046

**Pull request closed without merging**
